### ISSUE TITLE
Checkpoint 1 Ready For Review

### ISSUE THREAD

**Issue by AliviaK** [AliviaK/recipeSharing#1]
@pawaitemadisoncollege - Checkpoint 1 is ready for review!

**Comment by pawaitemadisoncollege** [comment]
@AliviaK!!!   What an awesome start to your indie project! Your problem statement and solution do an excellent job explaining the motivation behind your project and how your application will be different from those already on the market.  All of your documentation so far is of high quality and very thorough - it shows you've put quite a lot of time and thought into your indie project already.

A few thoughts: 

- [x] Screen design - great-looking home page.  Adding additional pages to cover the MVP will help you drive out the necessary db columns and flow.
- [x] I like that you've included options for both java mail and Amazon Rekognition. Since only one api is required, you might consider making one of those functionalities stretch goals rather than mvp. More about this in the next item...
- [x] I see three major areas of functionality that *could* be stretch goals (at least in terms of ent java project requirements): scaling, parties, and recipe reviews.  While they are all useful, I wonder if it might be a good idea to prioritize one of them as MVP and mark the others as stretch goals.  I don't want to discourage you from tackling everything you have marked as MVP, but I also don't want you to commit to too much!
- [x] Scaling and converting to volume/weight - are there any api out there that could help with this? If not, possible team project?
- [x] How is TogglTrack working for you? If you like it, it might be something share out in Slack, as I think others may find a good tracking tool really helpful!

I can't wait to see the first user stories built out for this! GREAT project idea!

**Comment by AliviaK** [comment]
Thank you! I will definitely keep adding to the screen designs for the additional pages, I think that would  be helpful too. 
And as far as hitting two apis and possibly too many large goals, I think prioritizing only one as the MVP makes sense to me because I don't want to under-deliver or try to do too much and not get it all done. I think I will modify my plan to make just javaMail the MVP so that the parties can still occur. And scaling/converting would be a perfect team project! 
I've found TogglTrack to work great, very convenient to have bookmarked to my browser and click stop/start whenever I am working on the project, so I will be sure to make a Slack post about it!

Thank you very much for the suggestions and advice!
